# Generated by Django 3.1.3 on 2023-03-26 05:35

from django.db import migrations, models
import home_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0013_fuel_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home_service.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('meta_title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
