# Generated by Django 3.1.3 on 2023-03-26 09:50

from django.db import migrations, models
import django.db.models.deletion
import home_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0014_pcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=home_service.models.get_file_path)),
                ('small_description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_service.pcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Spares',
        ),
    ]
