# Generated by Django 3.1.3 on 2023-03-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0017_auto_20230326_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
