# Generated by Django 3.1.3 on 2023-03-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0020_auto_20230331_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
