# Generated by Django 3.1.3 on 2023-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0021_auto_20230401_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_man',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fuel_man',
            name='doj',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fuel_man',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuel_man',
            name='service_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
