# Generated by Django 3.1.3 on 2023-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0023_forder_fstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FService_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('total', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
