# Generated by Django 3.1.3 on 2023-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0024_fservice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_man',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='fuel_man',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='fuel_man',
            name='experience',
        ),
        migrations.AddField(
            model_name='fuel_man',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
