# Generated by Django 3.1.3 on 2023-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0025_auto_20230401_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='FID_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
