# Generated by Django 3.1.3 on 2023-04-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0026_fid_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selectbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='service_man',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='service_man',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fuel_man',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_service.fstatus'),
        ),
        migrations.CreateModel(
            name='Selectmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('selectbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_service.selectbrand')),
            ],
        ),
    ]
