# Generated by Django 3.1.3 on 2023-04-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0027_auto_20230415_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_man',
            name='location',
        ),
        migrations.AddField(
            model_name='fuel_man',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fuel_man',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
