# Generated by Django 3.1.3 on 2023-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0028_auto_20230415_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_date',
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
