# Generated by Django 3.1.3 on 2023-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0029_auto_20230415_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forder',
            name='book_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='forder',
            name='vehicle_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='book_date',
            field=models.DateField(null=True),
        ),
    ]
