# Generated by Django 3.1.3 on 2023-04-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0032_auto_20230423_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brandd',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='modell',
        ),
    ]
