# Generated by Django 3.1.3 on 2023-04-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0034_auto_20230423_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
    ]
