# Generated by Django 3.1.3 on 2023-04-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0036_auto_20230423_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
