# Generated by Django 3.1.3 on 2023-04-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0041_auto_20230423_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selectbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selectmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('selectbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_service.selectbrand')),
            ],
        ),
    ]
